### PR TITLE
feat: wards for deployer contract

### PR DESCRIPTION
**Pull request by manuelpolzhofer**
Instead of removing the deployer as a ward from all contracts after the deployment.
Only permissioned addresses are allowed to call the deployer.

### CODE REVIEW

**Comment by manuelpolzhofer** [comment]
@lucasvo @ilinzweilin 
I added a new `resign` method to the deployer. We also need the wards because otherwise, it would be theoretically possible that somebody calls a deployMethod again during the deployment.

**Comment by lucasvo** [comment]
@manuelpolzhofer have you thought about adding a method that will call selfdestruct on the deployer? I think that would be handy

**Comment by manuelpolzhofer** [comment]
true. I always forget that solidity has this nice `selfdestruct()` functionality. On the other hand with the current implementation, it would be still possible to re-active the `deployer` again in case it is needed.

**Comment by lucasvo** [comment]
@manuelpolzhofer I think the selfdestruct would just be an option people could pick to be 100% certain that the deployer can't do anything anymore.

**Comment by lucasvo** [comment]
(i.e. it shouldn't be be a requirement)

**Pull request closed without merging**
